"""Theme definition: page tokens (CSS variables) plus a stage palette for animations.

A theme has three parts:

* ``tokens``: CSS custom properties for the page (colours, type scale, spacing).
  General CSS only uses the *semantic* names in ``SEMANTIC_TOKENS``, so any
  theme that defines them works with every component.
* ``stage``: literal colours for drawing on the animation stage, used by both
  ``manim_canvas.js`` and Manim scenes. Roles are generic (``primary``,
  ``highlight``, ...); each topic maps its own elements onto them.
* ``fonts``: serif / sans / mono stacks, plus optional web-font links.
"""

from __future__ import annotations

import dataclasses
import html
from dataclasses import dataclass, field

from .color import split_alpha

SEMANTIC_TOKENS = (
    "bg", "surface", "text", "text-soft", "rule",
    "primary", "primary-strong", "primary-soft", "on-primary", "on-gradient",
    "accent", "accent-soft", "accent-strong",
    "gradient-primary", "shadow-paper", "shadow-stage", "focus",
)

STAGE_ROLES = (
    "background",  # solid fallback / Manim background
    "grid", "axes", "text", "muted",
    "primary",     # main curve / series
    "highlight",   # key answers (e.g. roots)
    "point",       # notable point (e.g. vertex)
    "secondary",   # second series / intercepts
    "guide",       # guide lines (e.g. axis of symmetry)
    "warning",     # derived quantities worth calling out
    "plate",       # translucent label background
)

# Shared type scale, spacing and shape (from ethan-gueck.github.io tokens.css).
SCALE_TOKENS = {
    "fs-sm": "0.875rem",
    "fs-base": "1.125rem",
    "fs-md": "1.3125rem",
    "fs-lg": "1.625rem",
    "fs-xl": "clamp(2.5rem, 6vw, 4.25rem)",
    "space-1": "0.25rem",
    "space-2": "0.5rem",
    "space-3": "1rem",
    "space-4": "1.5rem",
    "space-5": "2.5rem",
    "space-6": "4rem",
    "radius-sm": "3px",
    "radius-md": "6px",
    "container": "1180px",
    "measure": "70ch",
}


@dataclass(frozen=True)
class Theme:
    name: str
    label: str
    tokens: dict[str, str]
    stage: dict[str, str]
    fonts: dict[str, str]
    stage_gradient: tuple[tuple[str, float], ...] = ()  # (colour, stop 0-1) pairs, drawn diagonally
    font_links: tuple[str, ...] = ()
    color_scheme: str = "light"
    extra: dict = field(default_factory=dict)

    def __post_init__(self):
        missing_tokens = [t for t in SEMANTIC_TOKENS if t not in self.tokens]
        missing_roles = [r for r in STAGE_ROLES if r not in self.stage]
        missing_fonts = [f for f in ("serif", "sans", "mono") if f not in self.fonts]
        if missing_tokens or missing_roles or missing_fonts:
            raise ValueError(
                f"Theme {self.name!r} is missing tokens={missing_tokens} stage={missing_roles} fonts={missing_fonts}"
            )

    # ---- Outputs --------------------------------------------------------------
    def css(self) -> str:
        """The theme as a ``:root { --token: value }`` stylesheet."""
        props = {**self.tokens, **{f"font-{k}": v for k, v in self.fonts.items()}}
        props.update({f"stage-{k}": v for k, v in self.stage.items()})
        if self.stage_gradient:
            stops = ", ".join(f"{c} {round(s * 100)}%" for c, s in self.stage_gradient)
            props["stage-gradient"] = f"linear-gradient(135deg, {stops})"
        else:
            props["stage-gradient"] = self.stage["background"]
        body = "\n".join(f"  --{k}: {v};" for k, v in props.items())
        return (
            f"/* Theme: {self.label}. Generated by general.themes; edit the Python theme, not this file. */\n"
            f":root {{\n  color-scheme: {self.color_scheme};\n{body}\n}}\n"
        )

    def head_links(self) -> str:
        """<link> tags for the theme's web fonts (empty if none)."""
        if not self.font_links:
            return ""
        preconnect = (
            '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
            '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
        )
        return preconnect + "\n".join(f'<link rel="stylesheet" href="{html.escape(url)}">' for url in self.font_links)

    def to_dict(self) -> dict:
        """What page scripts need: the stage palette and fonts."""
        return {
            "name": self.name,
            "stage": dict(self.stage),
            "stageGradient": [list(stop) for stop in self.stage_gradient],
            "fonts": dict(self.fonts),
            "colorScheme": self.color_scheme,
        }

    def manim_color(self, role: str) -> tuple[str, float]:
        """Stage role -> (hex, opacity), since Manim takes them separately."""
        return split_alpha(self.stage[role])

    def variant(self, name: str, label: str | None = None, **overrides) -> "Theme":
        """A new theme based on this one; dict fields are merged, not replaced.

        Example: ``PORTFOLIO.variant("portfolio-gold", stage={"primary": "#F2C14E"})``
        """
        merged = {}
        for key, value in overrides.items():
            current = getattr(self, key)
            merged[key] = {**current, **value} if isinstance(current, dict) else value
        return dataclasses.replace(self, name=name, label=label or name, **merged)
